### ISSUE TITLE
gradio has no attribute image editor since updating from 3.5.1 to 3.6.5

### ISSUE THREAD

**Issue by idronbes** [C0untFloyd/roop-unleashed#595]
i get this error when i run run.py

roop-unleashed\ui\tabs\faceswap_tab.py", line 77, in faceswap_tab
    maskimage = gr.ImageEditor(label="Manual mask Image", sources=["clipboard"], transforms="", type="numpy",
AttributeError: module 'gradio' has no attribute 'ImageEditor'

it was working with 3.5.1 version, but i decided to update to latest version.

**Comment by idronbes** [comment]
i ran the file  windows_run.bat in the installer folder, and looked for updates, and now it works
